### ISSUE TITLE
It can not run with a slight deviation

### ISSUE THREAD

**Issue by ghost** [havatv/qgisbosplugin#1]
The Number of steps must be great than 1 m (seems not to run when exactly at 1 m) and unallowed with a decimal, as well as the Start/End radius. The case I tested has an average error of 5 m around.
![1599215107(1)](https://user-images.githubusercontent.com/48680489/92230581-f42d1600-eedd-11ea-8778-3a5e94df2575.png)
![1599215127(1)](https://user-images.githubusercontent.com/48680489/92230591-f5f6d980-eedd-11ea-8d5b-82034fbd8aa4.png)
![1599215447(1)](https://user-images.githubusercontent.com/48680489/92230600-f8593380-eedd-11ea-8364-22c1df9c1d0b.png)

**Comment by havatv** [comment]
Thank you so much for reporting, and for your interest in the BOS plugin.

> The Number of steps must be great than 1 m (seems not to run when exactly at 1 m) and unallowed with a decimal, as well as the Start/End radius. The case I tested has an average error of 5 m around.

To allow calculation of statistics and plotting of the graphs, the number of steps has to be at least two.
I have now set the minimum number of steps to 2, avoiding that error.

Regarding decimals - since number of steps has to be an integer, decimals can not be allowed.

For start and end radius, decimals should be allowed, and it works for me:

![image](https://user-images.githubusercontent.com/1598812/92304663-432b8780-ef80-11ea-95fc-5e6e6608dbab.png)

 What happens when you try to use decimals?

**Comment by havatv** [comment]
I close the issue, since number of steps has been handled, and decimal numbers works works me where it is supposed to work. Please reopen if you still have issues with decimal numbers.

**Comment by havatv** [comment]
@fangmingLeee, I have uploaded version 1.1.0 of the BOS plugin to plugins.qgis.org. It will become available when it has been approved (hopefully soon).
Thanks again!
